# Environments
project_env: './env'

# Directories
## Classification
classif_splits_dir: 'data/classif_splits'
classif_train_outdir: 'out/classif_train_out'
best_classif_dir: 'out/best_classifier'
classif_benchmark_dir: 'out/benchmarks/classif'
classif_log_dir: 'out/logs/classif'

## NER
ner_splits_dir: 'data/ner_splits'
ner_checkpoint_dir: 'out/ner_checkpoints'
best_ner_dir: 'out/best_ner'


# Input files
classif_data: 'data/manual_classifications.csv'
ner_data: 'data/manual_ner_extraction.csv'

# File with configuration settings for the models
models: 'config/models_info.tsv'


# Number of epochs
classif_epochs: 10

# Number of threads, each gets 5 Gb
train_threads: 12

# Time for job
train_time: '24:00:00'