# Environments
project_env: './env'

# Directories
## Classification
classif_splits_dir: 'data/classif_splits'
classif_train_outdir: 'out/classif_train_out'
classif_benchmark_dir: 'out/benchmarks/classif'
classif_log_dir: 'out/logs/classif'

## NER
ner_splits_dir: 'data/ner_splits'
ner_checkpoint_dir: 'out/ner_checkpoints'


# Input files
classif_data: 'data/manual_classifications.csv'
ner_data: 'data/manual_ner_extraction.csv'

# Parameters
# Models
models:
  ['scibert']
  # ['bert', 'biobert', 'scibert', 'pubmedbert', 'pubmedbert_pmc',
  #   'bluebert', 'bluebert_mimic3', 'sapbert', 'sapbert_mean_token',
  #   'bioelectra', 'bioelectra_pmc', 'electramed', 'biomed_roberta',
  #   'biomed_roberta_chemprot', 'biomed_roberta_rct_500'
  #   ]

# Number of epochs
classif_epochs: 10

# Number of threads, each gets 5 Gb
train_threads: 12

# Time for job
train_time: '24:00:00'