# Environments
project_env: './env'

# Directories
## Classification
classif_splits_dir: 'data/classif_splits'
classif_train_outdir: 'out/classif_train_out'
best_classif_dir: 'out/classif_train_out/best'
classif_benchmark_dir: 'out/benchmarks/classif'
classif_log_dir: 'out/logs/classif'

## NER
ner_splits_dir: 'data/ner_splits'
ner_train_outdir: 'out/ner_train_out'
best_ner_dir: 'out/ner_train_out/best'
ner_benchmark_dir: 'out/benchmarks/ner'
ner_log_dir: 'out/logs/ner'

split_ratios: '0.8 0.1 0.1'


# Input files
classif_data: 'data/manual_classifications.csv'
ner_data: 'data/manual_ner_extraction.csv'
full_corpus: 'data/full_corpus.csv'

# File with configuration settings for the models
models: 'config/models_info.tsv'

# Dates used for initial query
initial_query_start: 2011
initial_query_end: 2021
query_string: 'config/query.txt'

# Number of epochs
classif_epochs: 10
ner_epochs: 10

# Number of threads, each gets 5 Gb
train_threads: 12

# Time for job
train_time: '24:00:00'