# Environments
project_env: './env'

# Directories

## Querying
query_out_dir: 'out/original_query'
last_date_dir: 'out/last_query_date'

## Classification
classif_splits_dir: 'data/classif_splits'
classif_train_outdir: 'out/classif_train_out'
classif_benchmark_dir: 'out/benchmarks/classif'
classif_log_dir: 'out/logs/classif'
classif_out_dir: 'out/original_query/classification'

## NER
ner_splits_dir: 'data/ner_splits'
ner_train_outdir: 'out/ner_train_out'
ner_benchmark_dir: 'out/benchmarks/ner'
ner_log_dir: 'out/logs/ner'
ner_out_dir: 'out/original_query/ner'

## URL Extraction
extract_url_dir: 'out/original_query/url_extraction'

## URL Checking
check_url_dir: 'out/original_query/url_checking'

## Name processing
processed_names_dir: 'out/original_query/processed_names'

## Initial deduplication
initial_dedupe_dir: 'out/original_query/initial_deduplication'

## Manual review
manual_review_dir: 'out/original_query/manual_review'

# Input files
classif_data: 'data/manual_classifications.csv'
ner_data: 'data/manual_ner_extraction.csv'

# File with configuration settings for the models
models: 'config/models_info.tsv'

# Dates used for initial query
initial_query_start: 2001
initial_query_end: 2021
query_string: 'config/query.txt'

# Ratios used for data splitting
split_ratios: '0.8 0.1 0.1'

# Metrics used for choosing best model/epoch
class_criteria_metric: 'precision'
ner_criteria_metric: 'precision'

# Number of epochs
classif_epochs: 10
ner_epochs: 10

# Filtering parameters
max_urls: 2
min_best_name_prob: 0.978
