# Environments
project_env: './env'

# Directories

## Querying
query_out_dir: 'out/new_query'
last_date_dir: 'out/last_query_date'

## Classification
classif_train_outdir: 'out/classif_train_out'
classif_out_dir: 'out/new_query/classification'

## NER
ner_train_outdir: 'out/ner_train_out'
ner_out_dir: 'out/new_query/ner'

## URL Extraction
extract_url_dir: 'out/new_query/url_extraction'

## URL Checking
check_url_dir: 'out/new_query/url_checking'