# Environments
project_env: './env'

# Directories

## Querying
query_out_dir: 'out/new_query'
last_date_dir: 'out/last_query_date'

## Classification
classif_train_outdir: 'out/classif_train_out'
classif_out_dir: 'out/new_query/classification'

## NER
ner_train_outdir: 'out/ner_train_out'
ner_out_dir: 'out/new_query/ner'

## URL Extraction
extract_url_dir: 'out/new_query/url_extraction'

## URL Checking
check_url_dir: 'out/new_query/url_checking'

## Filtering
filtered_results_dir: 'out/new_query/filtered_results'

## Deduplicating
deduplicated_dir: 'out/new_query/deduplicated_results'

# Filtering parameters
min_urls: 1
max_urls: 2
manual_review_prob: 0.95